# adsoft wype-api
application: tweet-webtoken-api
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: web_token_api.application
  secure: always

#- url: /favicon\.ico
#  static_files: favicon.ico
#  upload: favicon\.ico

- url: /app
  static_dir: app

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images  

- url: /js
  static_dir: js

- url: /scripts
  static_dir: scripts

- url: .*
  script: public_rest_api.app

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
