runtime: python27
api_version: 1
threadsafe: yes
handlers:

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts

- url: /app
  static_dir: app  

- url: /js
  static_dir: js

- url: .*
  script: main.app

- url: /login/.*
  script: users.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0
